export default{
  title:'Launch Your Spaceship.',
  subtitle:'Gate to the Evan Universe',
  emailLabel:'Email address',
  emailPlaceholder:'Enter email',
  pwdLabel:'Password',
  pwdPlaceholder:'Enter password',
  submit:'Launch',
  remember:'remember me',
  register:'Register',
  forget:'Forget password?',
  forgotten:'Plz contact the Administrator',
  noUser: 'Invalid username or password',
  welcome:'Welcome back',
}
